In [2]:
import numpy as np
an_array=np.array([3,33,333])#create a rank 1 array
print(type(an_array))

<class 'numpy.ndarray'>


In [3]:
#test the shape of array
print(an_array.shape)

(3,)


In [5]:
print(an_array[0],an_array[2])

3 333


In [7]:
an_array[0]=888
print(an_array)

[888  33 333]


# declaring 2D array

In [9]:
another=np.array([[11,12,13],[21,22,23]]) #createrank 2 array
print(another)
print("the shape is 2 row , 3 columns:",another.shape)
print("accessing elements [0,0],[0,1],and[1,0] of the ndarray:",another[0,0],",",another[0,1],",",another[0,2])

[[11 12 13]
 [21 22 23]]
the shape is 2 row , 3 columns: (2, 3)
accessing elements [0,0],[0,1],and[1,0] of the ndarray: 11 , 12 , 13


In [10]:
#create  a 2*2 array of zero
ex1=np.zeros((2,2))
print(ex1)

[[0. 0.]
 [0. 0.]]


In [11]:
#create a 2*2 array fillrd with 9.0
ex2=np.full((3,3),9.0)
print(ex2)

[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]


In [14]:
# CREATE matrix identity
ex3=np.eye(4,4)
print(ex3)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
#create array of one 
ex4=np.ones((2,1))
print(ex4)

[[1.]
 [1.]]


In [15]:
ex5=np.random.random((2,2))
print(ex5)

[[0.53309362 0.94489174]
 [0.11757266 0.16982714]]


In [3]:
an_array=np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [18]:
a_slice=an_array[0:2,1:3]
print(a_slice)

[[12 13]
 [22 23]]


In [19]:
print("before:", an_array[0,1])#inspect the elements at 0,1
a_slice[0,0]=1000
print("after:",an_array[0,1])

before: 12
after: 1000


In [21]:
list = [2, 4, 5, 6, 3, 6]
list[1]
list[2]


5

In [4]:
an_array=np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [5]:
row_rank1= an_array[1,:]#rank 1view
print(row_rank1,row_rank1.shape)

[21 22 23 24] (4,)


In [6]:
row_rank2=an_array[1:2, :] #rank 2 view
print(row_rank2,row_rank2.shape)

[[21 22 23 24]] (1, 4)


In [16]:
column_rank1=an_array[:,1]
column_rank2=an_array[:,1:2]
print(column_rank1,column_rank1.shape)

[12 22 32] (3,)


In [17]:
print(column_rank2,column_rank2.shape)

[[12]
 [22]
 [32]] (3, 1)


In [28]:
an_array=np.array([[11,12,13],[21,22,23],[31,32,33],[41,42,43]])
print('original Array:')
print(an_array)

original Array:
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [29]:
col_indices=np.array([0,1,2,0])
print('\ncol indices picked :',col_indices)
row_indices=np.arange(4)
print('\nRows indices picked :',row_indices)


col indices picked : [0 1 2 0]

Rows indices picked : [0 1 2 3]


In [30]:
# examiane the parings of row indices ans col_inices
for i,j in zip(row_indices,col_indices):
    print(i,", ",j)
''' for i in row_indices:
    for j in col_indices:'''

0 ,  0
1 ,  1
2 ,  2
3 ,  0


' for i in row_indices:\n    for j in col_indices:'

In [31]:
print('values in the array at those indices: ',an_array[row_indices,col_indices])

values in the array at those indices:  [11 22 33 41]


In [32]:
an_array[row_indices, col_indices]+=100000
print('\nChanges Array:')
print(an_array)


Changes Array:
[[100011     12     13]
 [    21 100022     23]
 [    31     32 100033]
 [100041     42     43]]


In [1]:
import numpy as np

In [2]:
an_array=np.array([[11,12],[21,22],[31,32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [3]:
filter=(an_array > 15)
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [6]:
print(an_array[an_array >15])

[21 22 31 32]


In [7]:
an_array[an_array %2==0]+=100
print(an_array)

[[ 11 112]
 [ 21 122]
 [ 31 132]]


In [8]:
ex1=np.array([11,12])
print(ex1.dtype)

int32


In [9]:
ex2=np.array([11.0,12.0])
print(ex2.dtype)

float64


In [10]:
ex3=np.array([11,12],dtype=np.int64)
print(ex3.dtype)

int64


In [12]:
ex4=np.array([11.1,12.7],dtype=np.int64)
print(ex4.dtype)
print()
print(ex4)

int64

[11 12]


In [13]:
ex5=np.array([11,21],dtype=np.float64)
print(ex5.dtype)
print()
print(ex5)

float64

[11. 21.]


In [16]:
x=np.array([[111,112],[121,122]] ,dtype=np.int)
y=np.array([[211,212],[221.1,222.1]] ,dtype=np.float)
print(x+y)
print()
print(np.add(x,y))

[[322.  324. ]
 [342.1 344.1]]

[[322.  324. ]
 [342.1 344.1]]


In [17]:
print(x-y)
print()
print(np.subtract(x,y))

[[-100.  -100. ]
 [-100.1 -100.1]]

[[-100.  -100. ]
 [-100.1 -100.1]]


In [18]:
print(x*y)
print()
print(np.multiply(x,y))

[[23421.  23744. ]
 [26753.1 27096.2]]

[[23421.  23744. ]
 [26753.1 27096.2]]


In [19]:
print(x/y)
print()
print(np.divide(x,y))

[[0.52606635 0.52830189]
 [0.54726368 0.54930212]]

[[0.52606635 0.52830189]
 [0.54726368 0.54930212]]


In [20]:
print(np.sqrt(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]]


In [21]:
print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


In [22]:
print(np.log(x))

[[4.7095302  4.71849887]
 [4.79579055 4.80402104]]


In [27]:
arr=10* np.random.randn(2,5)
print(arr)

[[  1.54771431 -15.28679517  -3.34585777  -6.39874326 -10.68743792]
 [ 12.14922239  -2.5863754   11.82357307 -36.65619055  15.88134152]]


In [28]:
print(arr.mean())


-3.3559548780400106


In [29]:
print(arr.mean(axis=1)) #axis 1=row 

[-6.83422396  0.1223142 ]


In [30]:
print(arr.mean(axis=0)) #axis 0= column

[  6.84846835  -8.93658529   4.23885765 -21.52746691   2.5969518 ]


In [31]:
print(arr.sum())

-33.55954878040011


In [32]:
print(np.median(arr,axis=1))

[-6.39874326 11.82357307]


In [33]:
unsorted=np.random.randn(10)
print(unsorted)

[ 2.16280233  1.17036409  0.40929379 -0.04343515  0.98576988 -1.28431509
  0.48834143 -1.15086489  0.43651741  0.47121888]


In [34]:
sorted=np.array(unsorted)
sorted.sort()
print(sorted)
print()
print(unsorted)

[-1.28431509 -1.15086489 -0.04343515  0.40929379  0.43651741  0.47121888
  0.48834143  0.98576988  1.17036409  2.16280233]

[ 2.16280233  1.17036409  0.40929379 -0.04343515  0.98576988 -1.28431509
  0.48834143 -1.15086489  0.43651741  0.47121888]


In [35]:
unsorted.sort()
print(unsorted)

[-1.28431509 -1.15086489 -0.04343515  0.40929379  0.43651741  0.47121888
  0.48834143  0.98576988  1.17036409  2.16280233]


In [36]:
array=np.array([1,2,1,4,2,1,4,2])
print(np.unique(array))

[1 2 4]


In [4]:
s1=np.array(['desk','chair','bulb'])
s2=np.array(['lamp','bulb','chair'])
print(s1,s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [5]:
print(np.intersect1d(s1,s2))

['bulb' 'chair']


In [6]:
print(np.union1d(s1,s2))

['bulb' 'chair' 'desk' 'lamp']


In [8]:
print(np.setdiff1d(s1,s2))

['desk']


In [9]:
print(np.in1d(s1,s2))

[False  True  True]


In [10]:
start=np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
add_rows=np.array([0,1,2])
print(add_rows)

[0 1 2]


In [12]:
y=start+add_rows
print(y)

[[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]


In [13]:
add_cols=np.array([[0,1,2,3]])
add_cols=add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [14]:
y=start+add_cols
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [16]:
add_scalar=np.array([1])
print(start+add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# example from the slides

In [8]:
arrA=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arrA)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
arrB = [0,1,0,2]
print(arrB)

[0, 1, 0, 2]


In [10]:
print(arrA+arrB)

[[ 1  3  3  6]
 [ 5  7  7 10]
 [ 9 11 11 14]]


In [19]:
from numpy import arange
from timeit import Timer

size=1000000
timeits=1000

In [20]:
nd_array=arange(size)
print(type(nd_array))

<class 'numpy.ndarray'>


In [22]:
timer_numpy=Timer("nd_array.sum()", "from __main__ import nd_array")
print("time is taken by numpy ndarray: %f seconds" %
      (timer_numpy.timeit(timeits)/timeits))

time is taken by numpy ndarray: 0.000922 seconds


In [24]:
a_list=list(range(size))
print(type(a_list))

<class 'list'>


In [30]:
timer_list=Timer("sum(a_list)", "from __main__ import a_list")
print("Time taken by list:  %f seconds" %
     (timer_list.timeit(timeits)/timeits))

Time taken by list:  0.063387 seconds


In [1]:
import numpy as np
x=np.array([23,23,24,24])

In [12]:
np.save('an_array',x)

In [13]:
np.load('an_array.npy')

array([23, 23, 24, 24])

## TEXT FORMAT

In [14]:
np.savetxt('array.txt',X=x,delimiter=',')
np.loadtxt('array.txt',delimiter=',')

array([23., 23., 24., 24.])

In [15]:
x2d=np.array([[1,1],[1,1]])# determine dot product of two matrices
y2d=np.array([[2,2],[2,2]])
print(x2d.dot(y2d))
print()
print(np.dot(x2d,y2d))


[[4 4]
 [4 4]]

[[4 4]
 [4 4]]


In [16]:
a1d=np.array([9,9])#to determine inner product of two vectors
b1d=np.array([10,10])
print(a1d.dot(b1d))
print()
print(np.dot(a1d,b1d))

180

180


In [17]:
ex1=np.array([[11,12],[21,22]])
print(np.sum(ex1))#sum elements in the array

66


In [18]:
print(np.sum(ex1,axis=0))

[32 34]


In [19]:
print(np.sum(ex1,axis=1))

[23 43]


In [24]:
x=np.random.randn(8)
y=np.random.randn(8)
print(x)
print()
print(y)
np.maximum(x,y)

[-0.35120213 -0.15424357 -0.17324626 -1.56441951  0.1991313   1.05518775
  1.19975223 -0.57306628]

[ 0.4299493  -1.00176172  2.28197067 -1.72853381 -0.8712104   3.41056862
  1.24885646 -2.30158751]


array([ 0.4299493 , -0.15424357,  2.28197067, -1.56441951,  0.1991313 ,
        3.41056862,  1.24885646, -0.57306628])

## reshaing array:

In [2]:
# grab values from 0 to 19 in an array
arr=np.arange(20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [3]:
#reshape to be a 4*5 matrix
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [4]:
#transpose
ex1=np.array([[11,12],[21,22]])
ex1.T

array([[11, 21],
       [12, 22]])

### indexing using where():

In [9]:
x_1=np.array([1,2,3,4,5])
y_1=np.array([11,22,33,44,55])
#where we have true in filter it will print x_1 value and for false y_1 value
#this is working of.where function
filter=np.array([True,False,True,False,True])

In [10]:
out=np.where(filter,x_1,y_1)
print(out)

[ 1 22  3 44  5]


In [12]:
mat=np.random.rand(5,5)
mat

array([[0.90364909, 0.9379358 , 0.12192896, 0.87109182, 0.10791175],
       [0.84280832, 0.87593915, 0.42640344, 0.91622057, 0.90177056],
       [0.21782035, 0.07208206, 0.41558294, 0.82125638, 0.21788882],
       [0.60023516, 0.41590226, 0.30480267, 0.27741895, 0.5050595 ],
       [0.21805157, 0.04626742, 0.18748189, 0.61564934, 0.78866399]])

In [15]:
np.where(mat>0.5, 1000, -1)

#if mat>0.5:
        #replace(1000)
#else:
         #replace(-1)"""

array([[1000, 1000,   -1, 1000,   -1],
       [1000, 1000,   -1, 1000, 1000],
       [  -1,   -1,   -1, 1000,   -1],
       [1000,   -1,   -1,   -1, 1000],
       [  -1,   -1,   -1, 1000, 1000]])

In [ ]:
#any or all conditionals:

In [16]:
arr_bools=np.array([True,False,True,False,True])

In [17]:
arr_bools.any()

True

In [18]:
arr_bools.all()

False

In [20]:
y=np.random.normal(size=(1,5))

In [21]:
z=np.random.randint(low=2,high=50,size=4)
print(z)

[44 21 10  4]


In [22]:
np.random.permutation(z)

array([21,  4, 10, 44])

In [23]:
np.random.uniform(size=4)

array([0.95298375, 0.46275688, 0.87734892, 0.20591504])

In [24]:
np.random.normal(size=4)

array([ 0.78173104,  0.6441417 , -0.41731015,  0.76718207])

In [25]:
k=np.random.randint(low=2,high=50,size=(2,2))
print(k)
print()
m=np.random.randint(low=2,high=50,size=(2,2))
print(m)

[[20 45]
 [21  5]]

[[40 27]
 [ 9 10]]


In [26]:
np.vstack((k,m))

array([[20, 45],
       [21,  5],
       [40, 27],
       [ 9, 10]])

In [27]:
np.hstack((k,m))

array([[20, 45, 40, 27],
       [21,  5,  9, 10]])